INSERT INTO public.achievement_request VALUES ('marione', 'cicc55', 'JACKPOT!!!', 0);
INSERT INTO public.achievement_request VALUES ('marass', 'marione', 'JACKPOT!!!', 0);
INSERT INTO public.achievement_request VALUES ('marione', 'scarredGio', 'JACKPOT!!!', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'marione', 'LA CUMMINA', 2);
INSERT INTO public.achievement_request VALUES ('cicc55', 'marione', 'IL RITORNO DEL BROLYCULO', 2);
INSERT INTO public.achievement_request VALUES ('marione', 'marass', 'THE STORM THAT IS APPROACHING', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'cicc55', 'GOURMET RACE', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'cicc55', 'IL RITORNO DEL BROLYCULO', 2);
INSERT INTO public.achievement_request VALUES ('cecia234', 'cicc55', 'PARITA’', 2);
INSERT INTO public.achievement_request VALUES ('cecia234', 'cicc55', 'ULTRA SIDE CHARACTER', 2);
INSERT INTO public.achievement_request VALUES ('cecia234', 'nupas', 'GOURMET RACE', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'nupas', 'GAMER ESPERTO', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'marass', 'GOURMET RACE', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'frass', 'GOURMET RACE', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'frass', 'GAMER ESPERTO', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'scarredGio', 'GOURMET RACE', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'scarredGio', 'GAMER ESPERTO', 0);
INSERT INTO public.achievement_request VALUES ('cecia234', 'marione', 'GAMER ESPERTO', 0);
INSERT INTO public.achievement_request VALUES ('marione', 'cecia234', 'GOURMET RACE', 2);
INSERT INTO public.achievement_request VALUES ('marione', 'cecia234', 'IL RITORNO DEL BROLYCULO', 2);
INSERT INTO public.achievement_request VALUES ('marione', 'cecia234', 'ULTRA SIDE CHARACTER', 2);
INSERT INTO public.achievement_request VALUES ('marione', 'cecia234', 'JACKPOT!!!', 2);
INSERT INTO public.achievement_request VALUES ('cecia234', 'marass', 'JACKPOT!!!', 0);